import { StyleSheet, Text, TouchableOpacity, View } from "react-native";

interface ChipPickerProps {
  label: string;
  options: string[];
  value: string;
  onChange: (next: string) => void;
  disabled?: boolean;
  /** Shown instead of chips when the option list is empty. */
  emptyHint?: string;
}

/**
 * Single-select chips for a short, known option list (periods "P1".."Pn", groups "G1".."Gm").
 *
 * A picker rather than free text because these labels are generated by the backend and the app
 * cannot correct a wrong one after upload — no endpoint rewrites period/group on an existing
 * session, so input-time correctness is the only correctness.
 *
 * A value that is not in `options` (a legacy free-text entry) is rendered as an extra selected
 * chip so it stays visible and can be replaced, rather than silently vanishing from the form.
 */
export function ChipPicker({
  label,
  options,
  value,
  onChange,
  disabled,
  emptyHint,
}: ChipPickerProps) {
  const shown = value && !options.includes(value) ? [...options, value] : options;

  return (
    <View style={styles.wrap}>
      <Text style={styles.label}>{label}</Text>
      {shown.length === 0 ? (
        <Text style={styles.emptyHint}>{emptyHint || "No options available."}</Text>
      ) : (
        <View style={styles.row}>
          {shown.map((opt) => {
            const selected = opt === value;
            const legacy = !options.includes(opt);
            return (
              <TouchableOpacity
                key={opt}
                style={[styles.chip, selected && styles.chipSelected, disabled && styles.chipDisabled]}
                onPress={() => !disabled && onChange(opt)}
                disabled={disabled}
                accessibilityRole="button"
                accessibilityState={{ selected }}
                accessibilityLabel={`${label} ${opt}${legacy ? " (not in this class)" : ""}`}
              >
                <Text style={[styles.chipText, selected && styles.chipTextSelected]}>{opt}</Text>
              </TouchableOpacity>
            );
          })}
        </View>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  wrap: { marginBottom: 18 },
  label: {
    fontSize: 17,
    color: "#333",
    marginBottom: 10,
    fontWeight: "600",
  },
  row: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#e8eaed",
    backgroundColor: "#f5f7fb",
    minWidth: 56,
    alignItems: "center",
  },
  chipSelected: { backgroundColor: "#1a73e8", borderColor: "#1a73e8" },
  chipDisabled: { opacity: 0.5 },
  chipText: { fontSize: 16, fontWeight: "600", color: "#5f6368" },
  chipTextSelected: { color: "#fff" },
  emptyHint: { fontSize: 15, color: "#9aa0a6" },
});
